spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging.level:
  org.hibernate:
    orm.jdbc.bind: trace

token:
  secret: test
  access-token-expiration-seconds: 7200 # 2시간
  refresh-token-expiration-seconds: 1209600 # 2주
  temporary-token-expiration-seconds: 600 # 10분

cloud:
  aws:
    s3:
      bucket: test
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: test
      secret-key: test
